name: pig_common
description: Shared code for the PiGation project.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  fixed: ^6.1.1

dev_dependencies:
  dcli: ^8.2.1
  lint_hard: ^6.2.1
  test: ^1.24.0
